// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJnFnCEDii3f1pld5_5WgafvAm21lgrU',
    appId: '1:1031487144351:web:3133a40e5639c1188e7daa',
    messagingSenderId: '1031487144351',
    projectId: 'social-media-app-bd3c4',
    authDomain: 'social-media-app-bd3c4.firebaseapp.com',
    storageBucket: 'social-media-app-bd3c4.appspot.com',
    measurementId: 'G-D0F3QS86TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJ3mPHtGpalwkiO1lwEArqTCTv94DxWc',
    appId: '1:1031487144351:android:9388d86f3b4aa36d8e7daa',
    messagingSenderId: '1031487144351',
    projectId: 'social-media-app-bd3c4',
    storageBucket: 'social-media-app-bd3c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjuXPAQswo80xH1i627TdqvO_K36Udo4',
    appId: '1:1031487144351:ios:48d150d9e6a963768e7daa',
    messagingSenderId: '1031487144351',
    projectId: 'social-media-app-bd3c4',
    storageBucket: 'social-media-app-bd3c4.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjuXPAQswo80xH1i627TdqvO_K36Udo4',
    appId: '1:1031487144351:ios:48d150d9e6a963768e7daa',
    messagingSenderId: '1031487144351',
    projectId: 'social-media-app-bd3c4',
    storageBucket: 'social-media-app-bd3c4.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJnFnCEDii3f1pld5_5WgafvAm21lgrU',
    appId: '1:1031487144351:web:edcceb545beb87a08e7daa',
    messagingSenderId: '1031487144351',
    projectId: 'social-media-app-bd3c4',
    authDomain: 'social-media-app-bd3c4.firebaseapp.com',
    storageBucket: 'social-media-app-bd3c4.appspot.com',
    measurementId: 'G-RR6W6GNKR1',
  );
}
